- name: Create tmp dir
  changed_when: false
  register: tmpDir
  tempfile:
    state: directory

- name: Clone scripts repo
  changed_when: false
  git:
    dest: "{{ tmpDir.path }}"
    repo: https://github.com/like-a-glitch/scripts.git

- name: Remove license and .git dir
  changed_when: false
  file:
    path: "{{ tmpDir.path }}/{{ item }}"
    state: absent
  loop: 
    - .git
    - LICENSE

- name: Copy scripts to /usr/local/bin/
  copy:
    dest: /usr/local/bin/
    mode: '755'
    src: "{{ tmpDir.path }}/"

- name: Remove tmp dir
  changed_when: false
  file:
    path: "{{ tmpDir.path }}"
    state: absent