- name: Install 'mpv'
  package:
    name: mpv

- name: Create config dir
  file:
    group: "{{ remote_user_name }}"
    mode: '700'
    owner: "{{ remote_user_name }}"
    path: "/home/{{ remote_user_name }}/.config/mpv"
    state: directory

- name: Copy keybindings file
  copy:
    dest: "/home/{{ remote_user_name }}/.config/mpv/input.conf"
    group: "{{ remote_user_name }}"
    mode: '664'
    owner: "{{ remote_user_name }}"
    src: input.conf

- name: Copy settings file
  copy:
    dest: "/home/{{ remote_user_name }}/.config/mpv/mpv.conf"
    group: "{{ remote_user_name }}"
    mode: '664'
    owner: "{{ remote_user_name }}"
    src: mpv.conf

- name: Create scripts dir
  file:
    group: "{{ remote_user_name }}"
    mode: '700'
    owner: "{{ remote_user_name }}"
    path: "/home/{{ remote_user_name }}/.config/mpv/scripts"
    state: directory

- name: Create tmp dir
  changed_when: false
  register: tmp_dir
  tempfile:
    state: directory

- name: Clone mpv_sponsorblock repo
  changed_when: false
  git:
    dest: "{{ tmp_dir.path }}"
    repo: https://github.com/po5/mpv_sponsorblock.git

- name: Copy sponsorblock files 1
  copy:
    dest: "/home/{{ remote_user_name }}/.config/mpv/scripts/"
    group: "{{ remote_user_name }}"
    mode: '755'
    owner: "{{ remote_user_name }}"
    src: "{{ tmp_dir.path }}/sponsorblock.lua"

- name: Copy sponsorblock files 2
  copy:
    dest: "/home/{{ remote_user_name }}/.config/mpv/scripts/"
    group: "{{ remote_user_name }}"
    mode: '755'
    owner: "{{ remote_user_name }}"
    src: "{{ tmp_dir.path }}/sponsorblock_shared"

- name: Remove tmp dir
  changed_when: false
  file:
    path: "{{ tmp_dir.path }}"
    state: absent