---

- become: true
  connection: local
  hosts: 
    - a-laptop
    - a-pc
  roles:
  # start
    - init
  # random
    - appsWithoutSetup
    - git
    - scripts
    - vscodium
    - zsh
  # end
    - autostart
    - keybindings
  vars_files:
    - vars.yml