---

- become: true
  connection: local
  hosts: localhost
  roles:
  # start
    - init
  # random
    - appsWithoutSetup
    - git
    - vscodium
    - zsh
  # end
    - autostart
  vars_files:
    - vars.yml