---

- become: true
  connection: local
  hosts: a-laptop
  roles:
  # start
    - init
  # random
    - appsWithoutSetup
    - git
    - scripts
    - thumbnailer
    - vscodium
    - zsh
  # end
    - autostart
    - keybindings
  vars_files:
    - vars.yml

- become: true
  connection: local
  hosts: a-pc
  roles:
  # start
    - init
  # random
    - appsWithoutSetup
    - dotnet
    - git
    - scripts
    - thumbnailer
    - vscodium
    - zsh
  # end
    - autostart
    - keybindings
  vars_files:
    - vars.yml