- name: Install 'codium'
  snap:
    classic: true
    name: codium

- name: Create config dir
  file:
    group: "{{ remote_user_name }}"
    mode: '700'
    owner: "{{ remote_user_name }}"
    path: "{{ config_path }}"
    state: directory

- name: Create config sub dir
  file:
    group: "{{ remote_user_name }}"
    mode: '775'
    owner: "{{ remote_user_name }}"
    path: "{{ config_path }}/User"
    state: directory

- name: Copy settings file
  copy:
    dest: "{{ config_path }}/User/settings.json"
    group: "{{ remote_user_name }}"
    mode: '664'
    owner: "{{ remote_user_name }}"
    src: settings.json

- name: Copy keybindings file
  copy:
    dest: "{{ config_path }}/User/keybindings.json"
    group: "{{ remote_user_name }}"
    mode: '664'
    owner: "{{ remote_user_name }}"
    src: keybindings.json

- name: Install extensions
  become_user: "{{ remote_user_name }}"
  changed_when: false
  command: "codium --install-extension {{ item }}"
  loop:
    - eamodio.gitlens
    - ms-toolsai.jupyter
    - muhammad-sammy.csharp
    - redhat.ansible
    - timonwong.shellcheck

- name: Set vscodium as default editor for multiple mime types
  become_user: "{{ remote_user_name }}"
  changed_when: false
  command: "xdg-mime default codium_codium.desktop {{ item }}"
  loop:
    - application/json
    - application/x-shellscript
    - application/x-yaml
    - application/xml
    - text/csv
    - text/markdown
    - text/plain
    - text/x-python

- name: Add to keybindings_dict
  set_fact:
    keybindings_dict: "{{ keybindings_dict | combine({'<Primary><Alt>c': 'codium'}) }}"