- name: Install 'codium'
  snap:
    classic: true
    name: codium

- name: Create config dir
  file:
    group: "{{ remoteUserName }}"
    mode: "u=rwx,g=,o="
    owner: "{{ remoteUserName }}"
    path: "{{ configPath }}"
    state: directory

- name: Create config sub dir
  file:
    group: "{{ remoteUserName }}"
    mode: "u=rwx,g=rwx,o=rx"
    owner: "{{ remoteUserName }}"
    path: "{{ configPath }}/User"
    state: directory

- name: Copy settings file
  copy:
    dest: "{{ configPath }}/User/settings.json"
    group: "{{ remoteUserName }}"
    mode: "u=rw,g=rw,o=r"
    owner: "{{ remoteUserName }}"
    src: settings.json

- name: Copy keybindings file
  copy:
    dest: "{{ configPath }}/User/keybindings.json"
    group: "{{ remoteUserName }}"
    mode: "u=rw,g=rw,o=r"
    owner: "{{ remoteUserName }}"
    src: keybindings.json

- name: Install extensions
  become_user: "{{ remoteUserName }}"
  changed_when: false
  command: "codium --install-extension {{ item }}"
  loop:
    - eamodio.gitlens
    - ms-toolsai.jupyter
    - redhat.ansible

- name: Set vscodium as default editor for multiple mime types
  become_user: "{{ remoteUserName }}"
  changed_when: false
  command: "xdg-mime default codium_codium.desktop {{ item }}"
  loop:
    - application/json
    - application/x-shellscript
    - application/x-yaml
    - application/xml
    - text/csv
    - text/markdown
    - text/plain