- name: Create config dir
  file:
    group: "{{ remote_user_name }}"
    mode: "700"
    owner: "{{ remote_user_name }}"
    path: "/home/{{ remote_user_name }}/.config/autostart"
    state: directory

- name: Copy autostart template
  loop: "{{ autostart_dict | dict2items }}"
  template:
    dest: "/home/{{ remote_user_name }}/.config/autostart/{{ item.key }}.desktop"
    group: "{{ remote_user_name }}"
    mode: "664"
    owner: "{{ remote_user_name }}"
    src: autostart.desktop.j2