---
- name: Install packages
  package:
    name:
      - deja-dup
      - libreoffice
      - mumble
      - pavucontrol
      - pdfarranger
      - simple-scan
      - syncthing-gtk

- name: Install flatpack packages
  flatpak:
    name: org.mozilla.Thunderbird

- name: Install snap packages
  snap:
    name:
      - keepassxc
      - signal-desktop
      - spotify

- name: Add to autostartDict
  set_fact:
    autostartDict: "{{ autostartDict | combine({ item.key : item.value }) }}"
  with_items:
    - { key: "signal-desktop", value: "signal-desktop --start-in-tray" }
    - { key: "syncthing-gtk", value: "syncthing-gtk" }
    - { key: "thunderbird", value: "flatpak run org.mozilla.Thunderbird" }

- name: Add to keybindingsDict
  set_fact:
    keybindingsDict: "{{ keybindingsDict | combine({ '<Primary><Alt>k' : 'keepassxc' }) }}"