---
- name: Install packages
  package:
    name:
      - deja-dup
      - libreoffice
      - mumble
      - pavucontrol
      - pdfarranger
      - python3-psutil
      - simple-scan
      - syncthing-gtk
      - vlc

- name: Install flatpack packages
  flatpak:
    name: org.mozilla.Thunderbird

- name: Install snap packages
  snap:
    name:
      - keepassxc
      - signal-desktop
      - spotify

- name: Add signal-desktop to autostartDict
  set_fact:
    autostartDict: "{{ autostartDict | combine({ 'signal-desktop' : 'signal-desktop --start-in-tray' }) }}"
  when: autostartSignal

- name: Add syncthing-gtk to autostartDict
  set_fact:
    autostartDict: "{{ autostartDict | combine({ 'syncthing-gtk' : 'syncthing-gtk' }) }}"

- name: Add thunderbird to autostartDict
  set_fact:
    autostartDict: "{{ autostartDict | combine({ 'thunderbird' : 'flatpak run org.mozilla.Thunderbird' }) }}"
  when: autostartThunderbird

- name: Add to keybindingsDict
  set_fact:
    keybindingsDict: "{{ keybindingsDict | combine({ '<Primary><Alt>k' : 'keepassxc' }) }}"