---
- name: Install packages
  package:
    name:
      - ansible-lint
      - deja-dup
      - exfatprogs
      - libreoffice
      - mumble
      - pavucontrol
      - pdfarranger
      - python3-psutil
      - simple-scan
      - streamlink
      - vlc

- name: Install flatpack packages
  flatpak:
    name: org.mozilla.Thunderbird

- name: Install snap packages
  snap:
    name:
      - keepassxc
      - signal-desktop
      - spotify

- name: Add signal-desktop to autostart_dict
  set_fact:
    autostart_dict: "{{ autostart_dict | combine({'signal-desktop': 'signal-desktop --start-in-tray'}) }}"
  when: autostart_signal

- name: Add thunderbird to autostart_dict
  set_fact:
    autostart_dict: "{{ autostart_dict | combine({'thunderbird': 'flatpak run org.mozilla.Thunderbird'}) }}"
  when: autostart_thunderbird

- name: Add to keybindings_dict
  set_fact:
    keybindings_dict: "{{ keybindings_dict | combine({'<Primary><Alt>k': 'keepassxc'}) }}"