---

- name: Install 'git'
  package:
    name: git

- name: Set init.defaultbranch
  become_user: "{{ remote_user_name }}"
  git_config:
    name: init.defaultbranch
    scope: global
    value: main

- name: Set user.email
  become_user: "{{ remote_user_name }}"
  git_config:
    name: user.email
    scope: global
    value: 156898711+like-a-glitch@users.noreply.github.com

- name: Set user.name
  become_user: "{{ remote_user_name }}"
  git_config:
    name: user.name
    scope: global
    value: like-a-glitch