- name: Set keybinding for web browser
  become_user: "{{ remoteUserName }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "['<Primary><Alt>b']"

- name: Set custom-keybindings binding
  become_user: "{{ remoteUserName }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ loop_index }}/binding"
    value: "'{{ item.key }}'"
  loop: "{{ keybindingsDict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Set custom-keybindings command
  become_user: "{{ remoteUserName }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ loop_index }}/command"
    value: "'{{ item.value }}'"
  loop: "{{ keybindingsDict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Set custom-keybindings name
  become_user: "{{ remoteUserName }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ loop_index }}/name"
    value: "'{{ item.value }}'"
  loop: "{{ keybindingsDict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Build keybindingsList
  set_fact:
    keybindingsList: "{{ keybindingsList | default([]) + [ singleQuote ~ '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom' ~ loop_index ~ '/' ~ singleQuote ] }}"
  loop: "{{ keybindingsDict | dict2items }}"
  loop_control:
    index_var: loop_index

- name: Set custom-keybindings array
  become_user: "{{ remoteUserName }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "{{ '[' ~ keybindingsList | join(', ') ~ ']' | string }}"