- name: Install 'virtualenv'
  package:
    name: virtualenv

# https://github.com/abcminiuser/python-elgato-streamdeck
- name: Install 'streamdeck'
  become_user: "{{ remoteUserName }}"
  pip:
    name:
      - pillow
      - streamdeck
    virtualenv: "/home/{{ remoteUserName }}/.virtualenv/streamdeck"

- name: Copy udev rules
  copy:
    dest: /etc/udev/rules.d/
    group: root
    mode: '644'
    owner: root
    src: 10-streamdeck.rules